### ISSUE TITLE
Please add on simple example to import users from csv file.

### ISSUE THREAD

**Issue by socialcyberdog** [FusionAuth/fusionauth-import-scripts#1]
Great to see this repository! It would be extremely helpful if you would like to add one simple example of importing a list of users from a csv file via bash. 

It is the first thing people want to do. Nobody will create users manually and it is somewhat of a stopper to first have to dig into api examples and fiddle with an unknown api. Certainly I would prefer to just replace a given csv file with my own users. This will be also very good for testing and gaining some experience with fusionauth.

Thanks!

**Comment by socialcyberdog** [comment]
You are missing a huge opportunity here to actually _pull in users_. 
The lack of import scripts lead to one potential customer choose a different solution this week.

**Comment by robotdan** [comment]
Thanks for the feedback @socialcyberdog . Have you had a chance to review our Import API? 

https://fusionauth.io/docs/v1/tech/apis/users#import-users

The code to read a CSV and then map that to JSON and call our Import API is fairly trivial. 

I do agree it will be valuable to add an example version of this code here in this repository. However we have a limited amount of resources, so we do the best that we can to prioritize them. 

We do encourage community participation, so if you would like to submit a PR with an example that would be great. 

Thanks for considering FusionAuth.

**Comment by socialcyberdog** [comment]
Because "rainy sunday" one more hint: loop over api is simple, yes, of course, but even for that some person needs programming skills. 

I do not want to spend my time trying to convince you why it is important to make _pulling in users_ as simple as possible. But I can tell you that an URL to an empty repository with recommendation of "program it yourself" is not what some people expect. 

Please do not misunderstand me, this is not a rant - I still totally like your product (and in fact I am able to code a simple import) - however I can report from real life that potential users exist that see this as a lack of usability and a lack of "integration mindset". BTW this goes side by side with missing integration for existing popular user databases and IAM systems. For a product like yours it might be a good assumption that some kind of user account management system already exists and easy integration is crucial. Adding simple gui config integration features with AD / big IAM solutions / custom DB will boost your popularity, I am sure. Good Luck!
