### ISSUE TITLE
Please add sql import example scripts

### ISSUE THREAD

**Issue by socialcyberdog** [FusionAuth/fusionauth-import-scripts#2]
Same like before, it would be great to be able to read an example sql import script - too many tables to guess what they need to generate a consistence test user db.

**Comment by voidmain** [comment]
@socialcyberdog - doing a direct SQL import is not recommended and scripts can break on new versions of FusionAuth since the database will change over time. We recommend using the Import API along with other APIs to get your data imported.

**Comment by robotdan** [comment]
+1 what @voidmain said. 

> doing a direct SQL import is not recommended 

.. and not supported at all. :-)
