### ISSUE TITLE
Please add script for generating 1 million fake users for testing

### ISSUE THREAD

**Issue by socialcyberdog** [FusionAuth/fusionauth-import-scripts#3]
I would like to experience how fusionauth feels with one million users. Please add a script that will create one million fake users for testing, thanks. I am sure you have such a script in your repo, but you did forget to add that to the public install package. Please, do not let us waste time reinventing that wheel, THANK YOU!

**Comment by robotdan** [comment]
Thanks for the request @socialcyberdog . 

Until this example is published, you can essentially just call the Create User API in a loop and increment the email address with an integer.  `exampleuser_$count@example.com`. 

https://fusionauth.io/docs/v1/tech/apis/users#create-a-user

**Comment by robotdan** [comment]
@socialcyberdog 
https://github.com/FusionAuth/fusionauth-import-scripts#generate-test-users
https://github.com/FusionAuth/fusionauth-import-scripts/blob/master/testing/generate_import.rb
