### ISSUE TITLE
Importing .NET hashed passwords

### ISSUE THREAD

**Issue by ashokgelal** [FusionAuth/fusionauth-import-scripts#4]
First of all, apologies if this is the wrong place to create this ticket. I'd be very happy to move it to a better place.

We are in the final phase of moving over to FusionAuth, the only last hurdle being existing users import.

We have a asp .net application that currently stores the hashed password using [this official algorithm](https://github.com/aspnet/AspNetIdentity/blob/master/src/Microsoft.AspNet.Identity.Core/Crypto.cs#L26). A small inconvenience that it concatenates both salt and password before saving it in the database.

I'm now trying to import existing users by first extracting the salt and password and then using the FusionaAuth C# client library to complete the import. The import completes successfully but my credentials don't seem to work. I would appreciate any help to get over this hurdle.

Here is how I'm doing the import (only one user for testing):

```csharp
private static string _fusionauthUrl = "http://localhost:9011";
private static string _fusionauthApiKey = "";
private static string _fusionauthApplicationId = "";
private static string _fusionauthTenantId = "";

static async Task Main()
{
    var registration = new UserRegistration {applicationId = new Guid(_fusionauthApplicationId)};
    const string hashedPassword = "AHo3m9v4b7Jv/ICDR3xvSnCXKk42TbUg/pN8+McB1W9kxabOcXgAAcGuXj9PnjeX/w==";
    var (salt, password) = ExtractSaltAndPassword(hashedPassword);

    var user = new User
    {
        username = "janedoe",
        email = "jane@example.com",
        registrations = new List<UserRegistration> {registration},
        verified = true,
        active = true,
        encryptionScheme = "pbkdf2hmacsha1",
        factor = 1000,
        salt = Convert.ToBase64String(salt),
        password = Convert.ToBase64String(password),
    };

    var request = new ImportRequest
    {
        users = new List<User> {user},
        validateDbConstraints = false
    };
    var client = new FusionAuthClient(_fusionauthApiKey, _fusionauthUrl, _fusionauthTenantId);
    var response = await client.ImportUsersAsync(request);
    Console.WriteLine(response.statusCode);
}
   
```

This is the salt and hash extraction logic:

```csharp
public static Tuple<byte[], byte[]> ExtractSaltAndPassword(string hashedPassword)
{
    var hashedPasswordBytes = Convert.FromBase64String(hashedPassword);
    var salt = new byte[SaltSize];
    Buffer.BlockCopy(hashedPasswordBytes, 1, salt, 0, SaltSize);
    var storedSubkey = new byte[PBKDF2SubkeyLength];
    Buffer.BlockCopy(hashedPasswordBytes, 1 + SaltSize, storedSubkey, 0, PBKDF2SubkeyLength);
    return Tuple.Create(salt, storedSubkey);
 }
```

I've created and successfully loaded an encryptor based on [this FusionAuth example encryptor](https://github.com/FusionAuth/fusionauth-example-password-encryptor/blob/master/src/main/java/com/mycompany/fusionauth/plugins/ExamplePBDKF2HMACSHA1PasswordEncryptor.java) with proper `keylength` and `defaultFactor`.

**Comment by robotdan** [comment]
That example you linked to above is sort of a unique implementation specific to a customer of ours that was importing from a legacy Oracle db. 

It may not be a good one to pull as an example. 

Do you have a known password, salt, hash etc to test with?

**Comment by ashokgelal** [comment]
I've a password and some hashes:

password: `supersecret`
Some hashes (with combined salt) [using this function](https://github.com/aspnet/AspNetIdentity/blob/master/src/Microsoft.AspNet.Identity.Core/Crypto.cs#L26):

`AJERV+ZvwakXg+AP09yPDJtwucf/9+jsoAGoeB8CMTzr0bsEQL3IQ4StQ/8/EmwHFA==`
`AEhNvtxbnvkRnAEPRS6ol0Edi+WF6AtXOwDk3Eck/dfeUpCulPX1yVU4G9UpFRycjQ==`
`AI0060+guxTYvJPL3kEqAzDwW3Avnpbd7+lTXM/K8ft7433JMy1PS/pSmhBIX3xotw==`
`AM0P7hfdDHw2d0Y9lZoxN9FY5v7rn8cfEL1AGngrNmFxZLPZs832m+lWPlPIepyuoQ==`
`AGlXna8THOKvQJGBFentzM11DRO65gdWYwrUM9G4iFKY2DFt4qFc1/O/zaFTEikaOA==`

**Comment by robotdan** [comment]
Try this

https://github.com/FusionAuth/fusionauth-example-password-encryptor/blob/master/src/main/java/com/mycompany/fusionauth/plugins/ExampleRfc2898DeriveBytesPasswordEncryptor.java

https://github.com/FusionAuth/fusionauth-example-password-encryptor/blob/master/src/test/java/com/mycompany/fusionauth/plugins/ExampleRfc2898DeriveBytesPasswordEncryptorTest.java

**Comment by ashokgelal** [comment]
That works!! You guys are the best! Thank you so much!!!

**Comment by robotdan** [comment]
You're welcome. Tell your friends! 😁

**Comment by ashokgelal** [comment]
I want to buy a Fusion Auth t-shirt right now and wear it proudly. Not sure if you guys have one. The level of support is beyond what I expected and beyond what I've got with any products. Mind blowing!

**Comment by robotdan** [comment]
We may set up a store front with merch at some point. For now, we'll send you a shirt by following the steps outlined on the download page.

https://fusionauth.io/download
